name: learn-github-actions
on: 
  push: 
    branches:
      - main
      - feature
env:
  SLACK_WEBHOOK: ${{secrets.GIT_HUB_ACTIONS_RUN}}
  SLACK_USERNAME: DeployBot
  SLACK_CHANNEL: お試し用
  SLACK_ICON: https://example.com/image/icon_bot.png
jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - name: Set deploy_branch
        run: |
         echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_ENV
            :
      - run: echo "${{ env.branch_name }}"
      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v4
        with:
         python-version: ${{ matrix.python-version }}
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          repository: gixo-jp/asahi-pos
          ref: ${{ env.branch_name }} 
    #-- Slack通知 --#
      # 成功
      - name: Slack Notification on Success
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Success
          SLACK_COLOR: good

      # 失敗
      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Deploy Failure
          SLACK_COLOR: danger
